# Project
name: incremental_ai
description: "An incremental UI-based video game using Flutter as game engine and UI framework."
version: 1.0.0

# Publishing
publish_to: 'none'
environment:
  sdk: ^3.9.0

# Dependencies
dependencies:
  # Flutter
  flutter:
    sdk: flutter

  # Logging
  logger: ^2.6.1

  # YAML
  yaml: ^3.1.3

  # Flutter It
  get_it: ^8.2.0
  watch_it: ^1.7.0

  # Fullscreen
  flutter_fullscreen: ^1.2.0

  # Animation
  flutter_animate: ^4.5.0

dev_dependencies:
  # Flutter
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0


# Flutter Options
flutter:
  # Enable material design
  uses-material-design: true

  # Load additional assets
  assets:
    - assets/translation/
    - assets/background/
